Pin mapping changes
lowRISC/cheriot-rtos pull request #19
Opened 2024-11-06 14:57 UTC by marnovandermaas

Mostly took Alex's changes for this. I tested this using Sonata software and it looks reasonable to me. @AlexJones0 feel free to change things if you think I am missing something.

2024-11-06 15:09 UTC, HU90m requested changes

2024-11-06 15:09 UTC, HU90m commented on sdk/boards/sonata-prerelease.json
>          },
```suggestion
        "spi_lcd": {
            "start" : 0x80300000,
            "end"   : 0x80302000
        },
```

2024-11-06 15:09 UTC, HU90m commented on sdk/boards/sonata-prerelease.json
>          },
```suggestion
        "spi_ethmac": {
            "start" : 0x80301000,
            "end"   : 0x80303000
        },
```

2024-11-06 15:09 UTC, HU90m commented on sdk/boards/sonata-prerelease.json
>          },
```suggestion
        "spi_board": {
            "start" : 0x80302000,
            "end"   : 0x80301000
        },
```

2024-11-06 17:36 UTC, HU90m commented on sdk/include/platform/sunburst/platform-pwm.hh
Could we hold off on pulling the PWM driver changes? I'm still not sure about them.

2024-11-07 13:23 UTC, AlexJones0 commented
Closed as superseded by #20.

2024-11-07 13:23 UTC, closed without merging