Update SPI driver to reflect register changes
lowRISC/cheriot-rtos pull request #4
Opened 2024-10-03 18:04 UTC by alees24

CS lines are now controlled by a register in the SPI controller itself.
FIFO depths are now available in the 'info' register, and the FIFOs are reduced to 16 entries apiece.

Ensure that zero-byte transfer requests do not result in a deadlock between software and hardware; the controller will attempt to start but cannot perform a zero-byte transfer.

Zero-byte blocking_write/read may be used instead to synchronise with the controller core.

2024-10-04 11:01 UTC, HU90m requested changes
Looks great happy to be merged as is. Only change required is to target the 'sonata' branch (not main).

2024-10-07 11:52 UTC, alees24 commented
Modified for 8-byte FIFOs.

2024-10-09 11:34 UTC, GregAC commented
@HU90m you happy for this to go in now? I'd like to unblock the SPI CS changes in sonata-system

2024-10-09 12:55 UTC, HU90m approved these changes

2024-10-09 12:55 UTC, merged